[package]
name = "asciiflow-media"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
encode-characterization = []
av1-encode-diagnostic = []

[dependencies]
libloading = "0.8"
asciiflow-core = { path = "../asciiflow-core" }
ffmpeg-sys-next.workspace = true
crossbeam-channel.workspace = true
libc = "0.2"
tracing.workspace = true
