[package]
name = "asciiflow-vulkan"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
build = "build.rs"

[features]
p010-output-diagnostic = []

[dependencies]
ash.workspace = true
asciiflow-core = { path = "../asciiflow-core" }
asciiflow-font = { path = "../asciiflow-font" }
bytemuck.workspace = true
gpu-allocator.workspace = true
tracing.workspace = true

[build-dependencies]
shaderc.workspace = true

[dev-dependencies]
asciiflow-cpu = { path = "../asciiflow-cpu" }
